services:
#    front.example:
#        class: FrontBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    form.flow.createPosteSecours:
        class: FrontBundle\Form\CreatePosteSecoursFlow
        parent: craue.form.flow