# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#  FOSUserBundle:
#      app_user.registration_listener:
#          class : AdminBundle/EventListener/Event
#          arguments: []
#          tags:
#              - { name: kernel.event_subscriber }

      app.form.registration:
          class: FrontBundle\Form\RegistrationFormType
          tags:
              - { name: form.type, alias: app_user_registration }



      app.form.profile:
                class: FrontBundle\Form\ProfileFormType
                tags:
                    - { name: form.type, alias: app_user_profile }


#      app.doctrine_image_uploader:
#              class: CommerceBundle\Entity\Upload
#              arguments: ['@commerce.image_uploader']
#              tags:
#                  - { name: doctrine.event_listener, event: prePersist }
#                  - { name: doctrine.event_listener, event: preUpdate }

