<?php

namespace AdminBundle\Repository;

/**
 * FormationPublicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormationPublicRepository extends \Doctrine\ORM\EntityRepository
{
}
