<?php

namespace CommerceBundle\Repository;

/**
 * OrganismRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganismRepository extends \Doctrine\ORM\EntityRepository
{
}
