<?php

namespace CommerceBundle\Repository;

/**
 * uploadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class uploadRepository extends \Doctrine\ORM\EntityRepository
{
}
